language: elixir
elixir:
  - 1.2.2
before_script:
  - mysql -uroot -e "create database phoenix_test"
  - mysql -uroot -e "grant all privileges on phoenix_test.* to phoenix@localhost identified by 'phoenix'"
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate

env:
  - MIX_ENV=test

script: mix coveralls.travis

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
